export const FLASHCARD_INDEX: Record<string, string[]> = {
  // --- UNIT 1 ---
  "U1-M1": ["Accrual Accounting", "Amortization", "Asset", "Balance Sheet", "Comprehensive Income", "Cost (noun)", "Cost of Goods Sold", "Depreciation", "Entity", "Equity", "Expense", "Expense Recognition", "Financial Accounting", "Firm", "Generally Accepted Accounting Principles (GAAP)", "Income Statement", "Inventory", "Liability", "Liquidity", "Management Accounting", "Matching", "Retained Earnings", "Return", "Revenue", "Solvency", "Statement of Financial Position (Balance Sheet)", "Value"],
  "U1-M2": ["Accounts Payable", "Asset", "Balance Sheet", "Common Stock", "Comprehensive Income", "Cost (noun)", "Cost of Goods Sold", "Credit", "Current Assets", "Depletion", "Depreciation", "Direct Labor Cost", "Entity", "Equity", "Expense", "Finished Goods Inventories", "Firm", "Goodwill", "Gross Profit Margin", "Income Statement", "Income Tax", "Intangible", "Inventory", "Investment", "Lease", "Liability", "Liquidity", "Manufacturing", "Manufacturing Cost", "Notes Payable", "Operations", "Overhead", "Property, Plant, and Equipment (PP&E)", "Receivable", "Retained Earnings", "Return", "Revenue", "Statement of Financial Position (Balance Sheet)", "Value"],
  "U1-M3": ["Accounts Payable", "Additional Paid-in Capital", "Amortization", "Asset", "Balance Sheet", "Board of Directors", "Business", "Business Combination", "Common Stock", "Comparability", "Comprehensive Income", "Consistency", "Consolidated Financial Statements", "Corporate Governance", "Cost (noun)", "Depreciation", "Dividend", "Entity", "Equity", "Expense", "Goodwill", "Income Statement", "Income Tax", "Internal Control", "Inventory", "Investment", "Liability", "Management", "Materiality", "Operations", "Provision", "Quality", "Reliability", "Resource Allocation", "Retained Earnings", "Return", "Revenue", "Stock Dividends", "System", "Valuation", "Value"],
  "U1-M4": ["Accounts Receivable", "Asset", "Bad Debts", "Balance Sheet", "Credit", "Expense", "Income Statement", "Liability", "Receivable", "Revenue", "Valuation"],
  "U1-M5": ["Asset", "Balance Sheet", "Business", "Cost (noun)", "Cost of Goods Sold", "Current Assets", "Entity", "Expense", "Finished Goods Inventories", "First-In-First-Out (FIFO)", "Gross Profit Margin", "Income Statement", "Inflation", "Inventory", "Liability", "Lower of Cost or Market Rule", "Manufacturing", "Moving Average", "Operations", "Valuation", "Value"],
  "U1-M6": ["Accelerated Depreciation", "Amortization", "Asset", "Balance Sheet", "Business", "Business Combination", "Common Stock", "Cost (noun)", "Debt Security", "Declining-Balance Method", "Depreciation", "Dividend", "Entity", "Equity", "Expenditure", "Expense", "Fixed Asset", "Goodwill", "Impaired Asset", "Income Statement", "Intangible", "Investment", "Liability", "Maintenance", "Property, Plant, and Equipment (PP&E)", "Recognition", "Research and Development Cost", "Revenue", "Straight-Line Method", "Valuation", "Value"],
  "U1-M7": ["Asset", "Balance Sheet", "Bond", "Bonds Payable", "Business", "Cost (noun)", "Effective Interest Rate", "Entity", "Expense", "Income Statement", "Liability", "Present Value", "Valuation", "Value", "Warranty"],
  "U1-M8": ["Amortization", "Asset", "Balance Sheet", "Business", "Cost (noun)", "Deferred Income Taxes", "Entity", "Equity", "Expense", "Income Statement", "Income Tax", "Incremental", "Lease", "Liability", "Operating Lease", "Operations", "Present Value", "Recognition", "Revenue", "Valuation", "Value"],
  "U1-M9": ["Asset", "Balance Sheet", "Business", "Completed-Contract Method", "Controls", "Cost (noun)", "Cost of Goods Sold", "Entity", "Expense", "Gross Profit Margin", "Income Statement", "Liability", "Operations", "Percentage-of-Completion Method", "Recognition", "Revenue", "Time Value of Money", "Valuation", "Value"],
  "U1-M10": ["Asset", "Balance Sheet", "Business", "Business Combination", "Consolidated Financial Statements", "Cost (noun)", "Depreciation", "Entity", "Equity", "Expense", "Goodwill", "Income Statement", "Investment", "Liability", "Revenue", "Value"],

  // --- UNIT 2 ---
  "U2-M1": ["Accounting", "Administrative Expense", "Allocation Base", "Asset", "Balance Sheet", "Budget", "Common Cost", "Conversion Cost", "Cost (noun)", "Cost Driver", "Cost Objects", "Cost Pools", "Cost of Goods Sold", "Department", "Depreciation", "Direct Cost", "Direct Labor Cost", "Direct Materials Cost", "Entity", "Expense", "Financial Accounting", "Finished Goods Inventories", "Fixed Cost", "Fixed Overhead", "Generally Accepted Accounting Principles (GAAP)", "High-low method", "Income Statement", "Indirect Cost", "Inventory", "Management Accounting", "Manufacturing", "Manufacturing Cost", "Mixed Cost", "Operations", "Overhead", "Period Cost", "Practical Capacity", "Prime Cost", "Product Cost", "Relevant Range", "Value", "Variable Cost", "Variable Overhead Expenses"],
  "U2-M2": ["Accounting", "Activity-Based Costing (ABC)", "Actual Cost", "Budget", "Cost (noun)", "Cost of Goods Sold", "Costing", "Department", "Direct Labor Cost", "Direct Materials Cost", "Downstream Costs", "Finished Goods Inventories", "Flexible Budget", "Job Order Costing", "Life-Cycle Costing", "Management-by-Exception", "Normal Cost", "Overhead", "Process Costing", "Prorate", "Standard Cost", "Static Budget", "Upstream Costs", "Variance", "Work-in-Process Inventory"],
  "U2-M3": ["Abnormal Spoilage", "Absorption Costing", "Asset", "Balance Sheet", "Budget", "Contribution Margin", "Cost (noun)", "Cost of Goods Sold", "Department", "Direct Cost", "Direct Labor Cost", "Direct Materials Cost", "Equivalent Units", "Expense", "Finished Goods Inventories", "Fixed Cost", "Fixed Overhead", "Generally Accepted Accounting Principles (GAAP)", "Gross Profit Margin", "Income Statement", "Indirect Cost", "Inventory", "Job Order Costing", "Normal Spoilage", "Operating Income", "Operations", "Overhead", "Overhead Rate", "Period Cost", "Process Costing", "Product Cost", "Revenue", "Value", "Variable Cost", "Variable Costing", "Work-in-Process Inventory"],
  "U2-M4": ["Activity-Based Costing (ABC)", "Activity-Based Management", "Allocation Base", "Asset", "Budget", "Byproduct", "Cost (noun)", "Cost Driver", "Cost Objects", "Cost Pools", "Cost of Goods Sold", "Department", "Direct Cost", "Direct Labor Cost", "Direct Materials Cost", "Direct Method", "Downstream Costs", "Dual Allocation Method", "Financial Accounting", "Gross Profit Margin", "Gross Profit Margin Percentage", "Indirect Cost", "Inventory", "Joint Product Costing", "Life-Cycle Costing", "Management Accounting", "Manufacturing", "Net Realizable Value", "Non-value Added", "Operations", "Overhead", "Process Analysis", "Process Costing", "Product Cost", "Reciprocal Allocation Method", "Resource Allocation", "Resource Driver", "Revenue", "Separable Costs", "Service Department", "Split-Off Point", "Step-Down Method", "Upstream Costs", "Value", "Value Chain", "Value-Added", "Variable Cost"],
  "U2-M5": ["Accounting", "Asset", "Budget", "Budgeting", "Business Process", "Capacity Management", "Capital Budgeting", "Continuous Improvement", "Cost (noun)", "Cost Management", "Demand", "Direct Labor Cost", "Direct Materials Cost", "Enterprise Resource Planning (ERP)", "Expense", "Fixed Cost", "Income Statement", "Inventory", "Just-In-Time Manufacturing (JIT)", "Lead Time", "Liability", "Maintenance", "Management", "Manufacturing", "Material Requirements Planning (MRP)", "Operations", "Outsourcing", "Practical Capacity", "Product Cost", "Quality", "Quality Control", "Resource Allocation", "Strategic Planning", "Supply", "Value"],
  "U2-M6": ["Appraisal Costs", "Batch Costing", "Benchmarking", "Best Practice", "Bottleneck", "Business Process", "Continuous Improvement", "Cost (noun)", "Cost Management", "Cost of Quality", "Direct Labor Cost", "Direct Materials Cost", "Downstream Costs", "Expense", "External Failure Costs", "Internal Failure Costs", "Inventory", "Just-In-Time Manufacturing (JIT)", "Life-Cycle Costing", "Management", "Manufacturing", "Non-value Added", "Operations", "Outsourcing", "Prevention Costs", "Process Analysis", "Product Cost", "Quality", "Reengineering", "Revenue", "Standard Cost", "Strategic Planning", "Upstream Costs", "Value", "Value Chain", "Value Engineering", "Value-Added"],

  // --- UNIT 3 ---
  "U3-M1": ["Asset", "Board of Directors", "Budget", "Budgeting", "Business Combination", "Capacity Management", "Capital Budget", "Capital Budgeting", "Cash Flow", "Contingency Planning", "Controls", "Cost (noun)", "Demand", "Disaster Recovery", "Divestiture", "Economies of Scale", "Exchange Rate", "Feedback", "Fixed Cost", "Forecast", "Foreign Exchange", "Goal Congruence", "Inflation", "Investment", "Learning Curve", "Management", "Operations", "Performance", "Performance Evaluation", "Quality", "Resource Allocation", "Return on Investment (ROI)", "Risk", "Strategic Business Unit (SBU)", "Strategic Planning", "Supply", "Value", "Variable Cost"],
  "U3-M2": ["Budget", "Budget Process", "Budgetary Slack", "Budgeting", "Capital Budget", "Cash Budget", "Continuous Improvement", "Controllable Cost", "Cost (noun)", "Cost of Goods Sold", "Direct Labor Cost", "Direct Materials Cost", "Expense", "Feedback", "Fixed Cost", "Flexible Budget", "Forecast", "Goal Congruence", "Inventory", "Management", "Master Budget", "Operations", "Performance", "Performance Evaluation", "Quality", "Revenue", "Standard Cost", "Strategic Planning", "Value", "Variable Cost", "Variance"],
  "U3-M3": ["Budget", "Budgeting", "Cash Flow", "Correlation", "Cost (noun)", "Cumulative Average-Time Learning Model", "Expected Value", "Fixed Cost", "Flexible Budget", "Forecast", "Inventory", "Learning Curve", "Management", "Mixed Cost", "Multiple Regression", "Probability", "Probability Distribution", "Regression Analysis", "Relevant Range", "Risk", "Sensitivity Analysis", "Simple Regression", "Value", "Variable Cost"],
  "U3-M4": ["Activity-Based Budgeting", "Balance Sheet", "Budget", "Budgeting", "Capital Budget", "Cash Budget", "Continuous Budget", "Cost (noun)", "Cost Driver", "Cost of Goods Sold", "Cost Pools", "Direct Cost", "Direct Labor Cost", "Direct Materials Cost", "Disbursement", "Financial Budget", "Finished Goods Inventories", "Forecast", "Income Statement", "Indirect Cost", "Management", "Manufacturing", "Master Budget", "Operating Budget", "Operations", "Overhead", "Pro Forma Statements", "Production Budget", "Project Budget", "Rolling Budget", "Sales Budget", "Standard Cost", "Statement of Cash Flow", "Value", "Zero-Based Budgeting"],
  "U3-M5": ["Absorption Costing", "Budget", "Budgeting", "Contribution Margin", "Cost (noun)", "Cost of Goods Sold", "Demand", "Direct Labor Cost", "Direct Materials Cost", "Expense", "Finished Goods Inventories", "Fixed Cost", "Fixed Overhead", "Forecast", "Gross Profit Margin", "Income Statement", "Inventory", "Management", "Manufacturing", "Master Budget", "Operating Budget", "Operating Income", "Operations", "Overhead", "Pro Forma Statements", "Production Budget", "Revenue", "Sales Budget", "Value", "Value Chain", "Variable Cost", "Variable Costing", "Variable Overhead Expenses"],
  "U3-M6": ["Asset", "Balance Sheet", "Budget", "Capital Budget", "Cash", "Cash Budget", "Cost (noun)", "Disbursement", "Dividend", "Forecast", "Income Statement", "Interest", "Liability", "Management", "Master Budget", "Operating Budget", "Operations", "Return", "Risk", "Value"],
  "U3-M7": ["Asset", "Balance Sheet", "Budget", "Capital Budget", "Cash", "Cash Budget", "Cost (noun)", "Cost of Goods Sold", "Debt Ratio", "Equity", "Expense", "Financial Statement", "Forecast", "Gross Profit Margin", "Income Statement", "Interest", "Liability", "Liquidity", "Management", "Net Income", "Operating Income", "Operations", "Pro Forma Statements", "Ratio Analysis", "Revenue", "Solvency", "Statement of Cash Flow", "Times Interest Earned", "Value"],

  // --- UNIT 4 ---
  "U4-M1": ["Actual Cost", "Asset", "Balanced Scorecard", "Budget", "Business Process", "Continuous Improvement", "Contribution Margin", "Cost (noun)", "Cost Center", "Cost Driver", "Department", "Direct Labor Cost", "Direct Materials Cost", "Efficiency (Usage) Variances", "Expense", "Feedback", "Fixed Cost", "Fixed Overhead", "Flexible Budget", "Forecast", "Investment Center", "Management", "Management-by-Exception", "Manufacturing", "Normal Spoilage", "Operating Income", "Operations", "Overhead", "Performance", "Performance Evaluation", "Price Variance", "Profit Center", "Relevant Range", "Responsibility", "Revenue", "Revenue Center", "Sales-Volume Variance", "Standard Cost", "Static Budget", "Unfavorable Variance", "Value", "Variable Cost", "Variance", "Work-in-Process Inventory"],
  "U4-M2": ["Actual Cost", "Allocation Base", "Budget", "Contribution Margin", "Cost (noun)", "Cost Driver", "Cost of Goods Sold", "Cost of Sales", "Direct Labor Cost", "Direct Materials Cost", "Expense", "Fixed Cost", "Fixed Overhead", "Fixed Overhead Spending Variance", "Flexible Budget", "Gross Profit Margin", "Mix Variance", "Operating Income", "Overhead", "Price Variance", "Production Volume Variance", "Revenue", "Sales-Mix Variance", "Sales-Volume Variance", "Standard Cost", "Static Budget", "Unfavorable Variance", "Unit Contribution", "Value", "Variable Cost", "Variable Overhead Efficiency Variance", "Variable Overhead Spending Variance", "Variance", "Yield Variance"],
  "U4-M3": ["Allocate", "Balanced Scorecard", "Budget", "Business Unit", "Centralization", "Common Cost", "Cost (noun)", "Cost Center", "Cost Objects", "Decentralization", "Department", "Expense", "Goal Congruence", "Incremental", "Investment Center", "Management", "Operations", "Performance", "Performance Evaluation", "Performance Measurement", "Profit Center", "Residual Income", "Responsibility", "Responsibility Center", "Return on Investment (ROI)", "Revenue", "Revenue Center", "Strategic Business Unit (SBU)", "Transfer Pricing", "Value"],
  "U4-M4": ["Absorption Costing", "Cost (noun)", "Decentralization", "Department", "Direct Labor Cost", "Direct Materials Cost", "Exchange Rate", "Expense", "Fixed Cost", "Fixed Overhead", "Full Cost", "Goal Congruence", "Management", "Market Price", "Negotiated Price", "Operations", "Opportunity Costs", "Overhead", "Performance", "Return", "Return on Investment (ROI)", "Revenue", "Segment", "Tariffs", "Transfer Pricing", "Value", "Variable Cost"],
  "U4-M5": ["Asset", "Balance Sheet", "Capital", "Capitalize", "Contribution Margin", "Controllable Cost", "Cost (noun)", "Cost Center", "Cost of Sales", "Current Assets", "Current Liability", "Depreciation", "Earnings", "Exchange Rate Risk", "Expense", "Expropriation Risk", "First-In-First-Out (FIFO)", "Fixed Cost", "Historical Cost", "Income Statement", "Inflation", "Insurance", "Interest", "Inventory", "Investment", "Investment Center", "Last-In-First-Out (LIFO)", "Management", "Market Value", "Non-value Added", "Operating Income", "Operations", "Opportunity Costs", "Performance", "Performance Measurement", "Political Risk", "Present Value", "Profit Center", "Quality", "Quotas", "Residual Income", "Return", "Return on Investment (ROI)", "Revenue", "Revenue Center", "Revenue Recognition", "Segment", "Tariffs", "Value", "Value-Added", "Variable Cost", "Variance", "Working Capital"],
  "U4-M6": ["Balanced Scorecard", "Best Practice", "Budget", "Cash Flow", "Cost (noun)", "Critical Success Factors", "Customer Satisfaction", "Cycle Time", "Database", "Discount", "Earnings", "Enterprise Resource Planning (ERP)", "Expense", "Gross Profit Margin Percentage", "Lead Time", "Liquidity", "Maintenance", "Management", "Operations", "Performance", "Price/Earnings (P/E) Ratio", "Productivity", "Quick Ratio", "Research and Development Cost", "Residual Income", "Return", "Return on Investment (ROI)", "Revenue", "Value", "Warranty"],

  // --- UNIT 5 ---
  "U5-M1": ["Accounting", "Annual Report", "Asset", "Audit", "Audit Committee", "Audit Report", "Authority", "Board of Directors", "Bottom-Up Approach", "Business", "Code of Conduct", "Committee of Sponsoring Organizations (COSO)", "Compensation", "Controls", "Corporate Governance", "Cost (noun)", "Disclosure", "Entity", "Financial Reporting", "Financial Statement", "Firm", "Fiscal Year", "Foreign Corrupt Practices Act", "Fraudulent", "Generally Accepted Accounting Principles (GAAP)", "Independent Auditor", "Internal Auditing", "Internal Control", "Liability", "Management", "Operations", "Organizational Culture", "Performance", "Public Company", "Public Company Accounting Oversight Board (PCAOB)", "Recognition", "Responsibility", "Risk", "Sarbanes-Oxley", "Shareholder", "System", "Top-Down Approach", "Value"],
  "U5-M2": ["Accounting", "Accounts Payable", "Accounts Receivable", "Accrued", "Application Controls", "Asset", "Audit", "Audit Committee", "Authority", "Board of Directors", "Business", "Business Unit", "Cash", "Committee of Sponsoring Organizations (COSO)", "Competence", "Confidentiality", "Control Risk", "Controls", "Cost (noun)", "Credit", "Customer Satisfaction", "Data Encryption", "Database", "Department", "Detection Risk", "Disaster Recovery", "Disbursement", "Distribution", "Encryption", "Enterprise-Wide", "Entity", "Exception Reporting", "Expected Value", "Expenditure", "Feedback", "Financial Statement", "Firewall", "Firm", "Flowchart", "Foreign Corrupt Practices Act", "Fraudulent", "Function", "Hardware", "Incremental", "Information System", "Information Technology (IT)", "Inherent Risk", "Input Controls", "Insurance", "Integrity", "Interest", "Internal Auditing", "Internal Control", "Internet", "Inventory", "Investment", "Joint Venture", "Journal", "Ledger", "Liability", "Lockbox System", "Maintenance", "Management", "Manufacturing", "Network", "Operations", "Output Controls", "Outsourcing", "Performance", "Portfolio", "Processing Controls", "Productivity", "Proxy", "Public Company", "Public Company Accounting Oversight Board (PCAOB)", "Quality", "Receivable", "Reconciliation", "Relevance", "Reliability", "Responsibility", "Return", "Return on Investment (ROI)", "Revenue", "Risk", "Sarbanes-Oxley", "Segregation of Duties", "Software", "Storage Controls", "Strategic Planning", "System", "Systems Development", "Taxation", "Top-Down Approach", "Transaction Processing", "Transmission", "Trojan Horse", "Utility", "Value", "Variance", "Virus", "Write-Off"],

  // --- UNIT 6 ---
  "U6-M1": ["Accounting", "Accounts Payable", "Accounts Receivable", "Allocate", "Balance Sheet", "Budget", "Budgeting", "Business", "Capital Budgeting", "Cash", "Cash Management", "Cost (noun)", "Cost System", "Credit", "Data Warehouse", "Database", "Database Management", "Disbursement", "Enterprise Resource Planning (ERP)", "Financial Reporting", "Financial Statement", "Fixed Asset", "Forecast", "Function", "Hardware", "Income Statement", "Information System", "Integrity", "Inventory", "Ledger", "Management", "Management Information System", "Manufacturing", "Operations", "Performance", "Pro Forma Statements", "Quality", "Quality Control", "Receivable", "Software", "Statement of Cash Flow", "System", "Transaction Processing", "Value", "Value Chain"],
  "U6-M2": ["Audit", "Board of Directors", "Business", "Cash", "Committee of Sponsoring Organizations (COSO)", "Controls", "Corporate Governance", "Cost (noun)", "Enterprise Resource Planning (ERP)", "Enterprise Risk Management (ERM)", "Entity", "Firewall", "Fraudulent", "Hardware", "Information Technology (IT)", "Internal Auditing", "Internal Control", "Journal", "Management", "Network", "Operations", "Performance", "Performance Measurement", "Risk", "Segregation of Duties", "Software", "System", "Value"],
  "U6-M3": ["Accounting", "Accounts Payable", "Accounts Receivable", "Budget", "Business", "Business Process", "Capital Investment", "Cash", "Cash Management", "Cost (noun)", "Database", "Encryption", "Firm", "Flowchart", "Hardware", "Information System", "Internet", "Investment", "Ledger", "Maintenance", "Management", "Network", "Operations", "Process Analysis", "Reengineering", "Risk", "Software", "System", "Systems Development", "Value", "Variance"],
  "U6-M4": ["Best Practice", "Budget", "Business", "Capital Budgeting", "Correlation", "Cost (noun)", "Cyclical", "Database", "Firm", "Forecast", "Information Technology (IT)", "Integrity", "Management", "Monte Carlo Technique", "Multiple Regression", "Performance", "Probability", "Probability Distribution", "Quality", "Regression Analysis", "Relevant Range", "Revenue", "Seasonal Trend", "Sensitivity Analysis", "Simple Regression", "Simulation", "Software", "Standard Deviation", "Strategic Planning", "System", "Time Series", "Value"],
  "U6-M5": ["Asset", "Business", "Correlation", "Cost (noun)", "Database", "Demand", "Expense", "Internet", "Management", "Network", "Quality", "Quality Control", "Software", "System", "Value"]
};
